"use client";

import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import "./globals.css";
import React from "react";
import { ThemeProvider, useTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { lightTheme, darkTheme } from "./theme";

import AppBar from './AppBar';

const baloo2 = Baloo_2({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const ThemeModeContext = React.createContext({
  mode: 'light',
  setMode: (_: 'light' | 'dark') => {},
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // On first mount, sync mode with localStorage, CSS variable, or system preference
  const [mode, setMode] = React.useState<'light' | 'dark' | null>(null);

  // On mount, determine mode from localStorage or system preference
  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      const stored = window.localStorage.getItem('theme');
      let initial: 'light' | 'dark' = 'light';
      if (stored === 'dark' || stored === 'light') initial = stored;
      else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) initial = 'dark';
      setMode(initial);
    }
  }, []);


  // Set --primary and --foreground CSS variables to match theme's primary and text color
  React.useEffect(() => {
    if (typeof window !== 'undefined' && mode) {
      document.documentElement.setAttribute('data-theme', mode);
      window.localStorage.setItem('theme', mode);
      const theme = mode === 'dark' ? darkTheme : lightTheme;
      document.documentElement.style.setProperty('--primary', theme.palette.primary.main);
      document.documentElement.style.setProperty('--foreground', theme.palette.text.primary);
    }
  }, [mode]);

  if (!mode) return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning></body>
    </html>
  );

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </head>
      <body suppressHydrationWarning>
        <ThemeModeContext.Provider value={{ mode, setMode }}>
          <ThemeProvider theme={mode === 'dark' ? darkTheme : lightTheme}>
            <CssBaseline />
            <AppBar />
            {children}
          </ThemeProvider>
        </ThemeModeContext.Provider>
      </body>
    </html>
  );
}
